AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM

Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.x
    Timeout: 5

Resource:
  eventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.hendler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
      FileUpload:
        Type: s3
        Properties:
          Bucket: !Ref MyBucket
          Events: s3:ObjectCreated:*

    MyBucket:
      Type: AWS::s3::Bucket

  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.hendler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post
